### ISSUE TITLE
User suggestion in assignee field

### ISSUE THREAD

**Issue by Pavangbhat** [Real-Dev-Squad/website-dashboard#103]
- [x] Make **Assigned To** label as Assignee
- [ ] For the Assignee input box there should be an autocompleting feature where **members** **usernames** should be suggested while providing input

References :point_down: 
https://github.com/Real-Dev-Squad/website-api-contracts/tree/main/members

**Comment by DeRaowl** [comment]
@Pavangbhat can this be picked?

**Comment by Pavangbhat** [comment]
Hi @DeRaowl 
Sorry for the late reply, I did not get any notification 
Yes you can start working on this task 
Meanwhile checkout [Real Dev Squad](https://www.realdevsquad.com/) and feel to reach out to any of our members to join the community
