### ISSUE TITLE
Dashboard form enhancement 

### ISSUE THREAD

**Issue by Pavangbhat** [Real-Dev-Squad/website-dashboard#106]
- [x] Let all the Textboxes have a useful placeholder such as an **example** or **description** 

- [x] Change Label name for **Ended** as **Ends on**

- [x] Expect **Title** all other input boxes(Including **started on** and **ends on**) should be hidden and should have an **EDIT** button/text that will act as a trigger to display the input box and once input has been provided with data, input box needs to be hidden and entered input must be displayed on the side of the edit button (Reach out design team for suggestions)

- [x] Move **noteworthy task** below **Title**

- [x] Change default value for following **Completion Award: Dinero:1000**,**Loss Rate:Dinero:100**  and if its a **noteworthy task** the dafult value for **Completion Award: Dinero:** should be **2500**

- [x] Let date have a default value of **7 days** and display the date such as **7 days remaining**

- [x] Default value for **Status** should be **active**

**Comment by NetanelK** [comment]
Hi, you can see in my branch the dashboard  enhancement

**Comment by Pavangbhat** [comment]
Thank you @NetanelK  :innocent:

**Comment by NetanelK** [comment]
Happy to help 😃

**Comment by Pavangbhat** [comment]
Hi @NetanelK 
Checkout [realdevsquad](https://www.realdevsquad.com/) and feel free to reach out to any of our members to get invited to our discord server
