### ISSUE TITLE
Move Edit Below Field's Name

### ISSUE THREAD

**Issue by lakshayman** [Real-Dev-Squad/website-dashboard#109]
The task is to move the edit below the field's name. 
For every field which has an edit

![Capture](https://user-images.githubusercontent.com/45519620/142285689-31e6d8b9-c32d-4e51-8207-a5646ada922f.PNG)

It should look like this

![img](https://user-images.githubusercontent.com/45519620/142285412-e39eb5e8-ad86-4edb-b7f5-8dc1e21ab8d5.png)

Notice the reduced opacity of "Edit". Upon hovering, it should be darker.
For reference check this PR: https://github.com/Real-Dev-Squad/website-dashboard/pull/108

**Comment by NetanelK** [comment]
@lakshayman As I made the previous change I can continue working on this

**Comment by NetanelK** [comment]
Add requested fix to #106
