### ISSUE TITLE
Enhance Ends on section in create task form

### ISSUE THREAD

**Issue by Pavangbhat** [Real-Dev-Squad/website-dashboard#111]
- [ ] Default ends on date should be 7 days 
- [ ] Move number of days remaining on **Ends on line** for eg: **Ends on:\*  2021-11-26 7 days remaining**
- [ ] Once date has been set date picker, input box must be hidden if date is valid
- [ ] Remove all commented lines in **setEndDate** function
![image](https://user-images.githubusercontent.com/45538392/142431475-03f25dfb-d9e6-4989-bb61-9c5c2eeec5fc.png)

**Comment by ojas-elawadhi** [comment]
I would like to take this task.
