### ISSUE TITLE
Fix missing edit button on Assigned To field 

### ISSUE THREAD

**Issue by Pavangbhat** [Real-Dev-Squad/website-dashboard#116]
![image](https://user-images.githubusercontent.com/45538392/143452348-8ce041dc-7820-4b82-a1af-603958a8aa3c.png)
- [x] Change **Assigned To**  as **Assginee** 
- [x] Add edit button on Assignee

Reference: https://github.com/Real-Dev-Squad/website-dashboard/pull/108

**Comment by ojas-elawadhi** [comment]
please assign this

**Comment by ojas-elawadhi** [comment]
Do I also need to change the placeholder from **Assigned to**  as **Assignee**?
![image](https://user-images.githubusercontent.com/83074474/144701607-80a6492f-52f5-4126-a84c-d49b723d4db6.png)

**Comment by Pavangbhat** [comment]
Let the place holder be an example
