### ISSUE TITLE
Text should not be selectable 

### ISSUE THREAD

**Issue by Pavangbhat** [Real-Dev-Squad/website-dashboard#123]
![image](https://user-images.githubusercontent.com/45538392/147377470-76b79c9a-64f2-4291-ba11-6c6f94cea043.png)

**Comment by vinayak-trivedi** [comment]
Hey Pawan I want to help in this.

**Comment by Pavangbhat** [comment]
Hi @vinayak-trivedi please go ahead with the task and go through **README.md**
