### ISSUE TITLE
Title should have focus by default when page loads

### ISSUE THREAD

**Issue by Pavangbhat** [Real-Dev-Squad/website-dashboard#124]
![image](https://user-images.githubusercontent.com/45538392/147377517-a6d311dd-a678-4c51-adab-30ef1ea9a5be.png)

**Comment by vinayak-trivedi** [comment]
Hey I can help with this as well.

**Comment by Pavangbhat** [comment]
The goal of this issue is that a new member can learn how to raise a PR and use Github, since you already got an idea let any new member take it up

**Comment by Srinu126** [comment]
I think i can fix the issue

**Comment by Pavangbhat** [comment]
Hi  @Srinu126
I have assigned you the task please follow contributing document

**Comment by Srinu126** [comment]
I am getting this error time and again when i am pushing the commit 
**remote: No anonymous write access. 
fatal: Authentication failed for 'https://github.com/Srinu126/website-dashboard.git/'**

**Comment by Pavangbhat** [comment]
Are you using Linux ?
Did you google why that is happening?

**Comment by Srinu126** [comment]
Yeah i figured it out and I have raised a pull request.
