### ISSUE TITLE
<Identity Service Health Check> Display health status

### ISSUE THREAD

**Issue by lakshayman** [Real-Dev-Squad/website-dashboard#132]
Create a user interface to display the health status of the identity service of every member to superuser only.

To obtain health logs:
- Request on `/logs?[filter]` to receive the health status data.

For now, mock the data as API is not ready.
Mock Data should be like:
```
logs: [
  {
    type: "identityHealth",
    timestamp: <timestamp>,
    payload: {
      username: <username>,
      serviceRunning: true/false
    }
  },
]
```

Display received health logs as specified.
![12222](https://user-images.githubusercontent.com/45519620/148779127-35a1e4f3-78a7-497e-af84-fec44e1d5a56.PNG)

Parent issue : [here](https://github.com/Real-Dev-Squad/identity-service/issues/15)

**Comment by ojas-elawadhi** [comment]
assign me please
