### ISSUE TITLE
Reason for profieDiff approval and rejection

### ISSUE THREAD

**Issue by lakshayman** [Real-Dev-Squad/website-dashboard#150]
In this PR(https://github.com/Real-Dev-Squad/website-dashboard/pull/142), we are sending a message field in the body while approving or rejecting a profileDiff, currently, we are sending it empty.

You have to create a message box that will appear when we click approve or reject, it should have a label saying `Reason for Approval/Rejection`, a text box, and two options `Send`, `Cancel`.

Send - will send the message in the text box.
Cancel - will terminate the process.

**Comment by RahulGoyal-tech** [comment]
Sent the changes in concerned PR.
