### ISSUE TITLE
Cookies are not being sent with the request POST `/task` request when submit button is clicked

### ISSUE THREAD

**Issue by whyDontI** [Real-Dev-Squad/website-dashboard#17]

**Comment by swarajpure** [comment]
The fetch call in `script.js` needs a cookie to be sent with it -- so the user who's making the request is authentincated

But we're not sending the cookie right now, which needs to be fixed.
Read more here: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#sending_a_request_with_credentials_included

**Comment by nilisha-jais** [comment]
I want to work on it

**Comment by akankshadharkar** [comment]
Sure @nilisha-jais 
I'll assign the task to you :)
Are you part of our discord channel, as well? 
It'd be a good place if you want to discuss progress/doubts/requirements of the task (and any future tasks 😄 )
Here is the link - https://discord.gg/9vXmZGTm

**Comment by nilisha-jais** [comment]
> Sure @nilisha-jais
> I'll assign the task to you :)
> Are you part of our discord channel, as well?
> It'd be a good place if you want to discuss progress/doubts/requirements of the task (and any future tasks 😄 )
> Here is the link - https://discord.gg/9vXmZGTm

I am already a part of the channel 😄
