### ISSUE TITLE
Issue in Assignee field | Autocomplete search

### ISSUE THREAD

**Issue by DeRaowl** [Real-Dev-Squad/website-dashboard#177]
Currently when we are entering any name it is listing all the members of RDS. Can we create scroll bar so that it will only take fixed width for auto complete.

Snippets for reference:
![image](https://user-images.githubusercontent.com/26904087/178026120-01c1d6be-7e73-4eea-ab13-b3e6bce36a06.png)
![image](https://user-images.githubusercontent.com/26904087/178026177-c69e9ab8-db11-4692-a35a-d9b61ee63086.png)

**Comment by rajat-mehra05** [comment]
Can you assign me this task ? Thanks.

**Comment by DeRaowl** [comment]
Assigned to you
