### ISSUE TITLE
Add <createdBy> and <assignedTo> fields in the task creation form

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-dashboard#18]
~While creating a task, we should be sending `participants` array which contains the users to which the task is to be assigned.
As of now, the array will contain only one user, which needs to be read from an input box.~

Currently we have an "ownerId" field in the response, we want to remove that and instead be sending:
- createdBy
- assignedTo

These will contain the respective userIds of the user who has created the task and the user who the task has been assigned to
You can refer this contract https://github.com/Real-Dev-Squad/website-api-contracts/blob/main/tasks/README.md

**Comment by dimky01** [comment]
Hi, I will like to work on this issue but I need more clarification. 
Do you mean that the dataToBeSent should have an array of "ownerId"?

**Comment by akankshadharkar** [comment]
Hey @dimky01, glad to have you here 😄 
I've updated the description, please feel free to reach out if you have any queries 
You can also join our discord channel if you'd like to be a part of our community - https://discord.gg/mppVvGhc

**Comment by dimky01** [comment]
Hi @akankshadharkar. I tried to make the changes and the run locally but I couldn't submit the form because I guess the POST Api handling the form submission needs to be updated as well. Is there any information on that or can I get access to make the required modification at the backend

**Comment by swarajpure** [comment]
> Hi @akankshadharkar. I tried to make the changes and the run locally but I couldn't submit the form because I guess the POST Api handling the form submission needs to be updated as well. Is there any information on that or can I get access to make the required modification at the backend

Yes, the API won't work. It'll give you CORS error as you're trying to access `api.realdevsquad.com` from `localhost`
Also, even if that was working, the API give error as we don't (yet) allow `assignedTo` field to be passed in `req.body`. We are validating the data coming through `req.body` [here](https://github.com/Real-Dev-Squad/website-backend/blob/develop/middlewares/validators/tasks.js).

Also, we had a discussion later on this issue and we had finalized that we won't be sending `createdBy` field from the frontend. Instead backend will pick that up from the cookie which is being sent. Why? The reason is stated [here](https://github.com/Real-Dev-Squad/website-backend/issues/306)

So can you please make a PR with the changes you've done? We could review and suggest changes -- if any 🙂

**Comment by dimky01** [comment]
Hi @swarajpure I have created a PR
