### ISSUE TITLE
Fix submit handler on task creation - Dashboard Site

### ISSUE THREAD

**Issue by iAmAshuSahoo** [Real-Dev-Squad/website-dashboard#180]
1. Show spinner till the request is in progress when submit is clicked.
2. Task gets submitted when Assignee name is empty
3. Prevent submitting a form on keypress of "Enter"
4. Write puppeteer test cases

**Comment by iAmAshuSahoo** [comment]
All the information
1. Screenshots of the working solution.
2. Issue explanations 
are available in the below link.

https://github.com/Real-Dev-Squad/website-dashboard/pull/178

**Comment by Pavangbhat** [comment]
Hi @muskanbatra-dev this task is completed 
There are a few open issues you can ping in the dashboard-site in discord
