### ISSUE TITLE
Add two new fields in the `Create Task` form

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-dashboard#189]
Add the following data fields required for the Leveling of Tasks
- Add a category field
- Add a level field

For reference : https://github.com/Real-Dev-Squad/todo-action-items/issues/72

**Comment by chiranjeevkapoor** [comment]
is this still available, can you pls explain exactly what needs to be done and in which file?

**Comment by rohan09-raj** [comment]
> is this still available, can you pls explain exactly what needs to be done and in which file?

It is already assigned, you can check the Assignees Section and it has already a PR linked with it. 🙂
