### ISSUE TITLE
Color highlight feature for profile diff data 

### ISSUE THREAD

**Issue by vin18** [Real-Dev-Squad/website-dashboard#200]
### Issue
- Add a color highlight feature similar to Github that shows users' profile data differences in red and green color. 

### Description
- Currently, we are showing old data and new data as profile differences on the profile page. The UX can be improved by highlighting the old data with red background color and newly changed data in the green background color. This feature would be similar to Github's commit diff feature. 
- The data field which is not modified will not have any background color.

**Comment by vin18** [comment]
I am taking up this issue.

**Comment by RitikJaiswal75** [comment]
Vinit this issue could use a little more description

**Comment by vin18** [comment]
> Vinit this issue could use a little more description

Updated. Thank you for the feedback,
