### ISSUE TITLE
Stop tests on push

### ISSUE THREAD

**Issue by RitikJaiswal75** [Real-Dev-Squad/website-dashboard#202]
## Issue
- When a PR is created, the git workflow runs tests on all the pull requests, but once the tests are run on pull requests they run again during push

### When was the issue discovered?
- The issue was discovered on 18th August 2022 during a hangout call while trying to merge PRs.

### Files that might be creating this
- `.github/workflows/test.yml`

### Screenshot of the Problem
![image](https://user-images.githubusercontent.com/57758447/185927191-4f7245d6-44b9-46a7-a355-b49ec54ef8b8.png)

**Comment by vin18** [comment]
Kindly assign this issue to me. I would be happy to dive and learn about GitHub workflow.

**Comment by vin18** [comment]
I got it that we don't need to run GitHub action twice for a PR. We don't need to run GitHub action for every push too, right? @RitikJaiswal75

**Comment by RitikJaiswal75** [comment]
> I got it that we don't need to run GitHub action twice for a PR. We don't need to run GitHub action for every push too, right? @RitikJaiswal75

Every time we update the PR the check should run but only once on every update currently there are 2 same checks that run as shown in ss. I want only 1 check to run.

**Comment by vin18** [comment]
I have done the changes and have raised PR for the same. Thanks, @RitikJaiswal75

**Comment by RitikJaiswal75** [comment]
This issue is solved by the below-mentioned PR:
https://github.com/Real-Dev-Squad/website-dashboard/pull/213
