### ISSUE TITLE
Refactor task form

### ISSUE THREAD

**Issue by whyDontI** [Real-Dev-Squad/website-dashboard#21]
## To Do
- Mark required fields with `*`
- Change `Gold, Silver, Bronze` to `Dinero & Neelam`
- Prefill default values
  - Dinero - 100
  - Neelam - 0
  - Percent completed - 0
  - Started - today's date
  - Status - pending
  - Preselect `Dev` in radio buttons `Dev / Group`
- Keep submit button disabled till all the required fields are filled without any errors

**Comment by bhk31** [comment]
I will be working on this.

**Comment by bhk31** [comment]
@whyDontI I have Few questions.

- Which fields are required in form or all are required ?
- You said Gold, Silver, Bronze to Dinero & Neelam So for Gold => Dinero, Silver => Neelam What about Bronze? Or Do we need to keep two only Dinero & Neelam.
-

**Comment by whyDontI** [comment]
1) Required fields
- title
- purpose
- type
- startedOn
- status
- ownerId 

2) Only Dinero and Neelam
