### ISSUE TITLE
Table View and Tile View Screen for the Users on the User Management 

### ISSUE THREAD

**Issue by heyrandhir** [Real-Dev-Squad/website-dashboard#227]
On the dashboard Site, there will be a button called User Management that should only be visible to super users. On clicking that the User will be directed to the Listing Screen. This screen will list all the Users in the tile view or table view.  There should be a toggle button on top to switch between both modes. Also, a search bar at the top to search for specific users.

Note: The page should be responsive. We need to also write unit and integration tests and also take care of accessibility. 

Refer to this [figma link](https://www.figma.com/file/UsEeJHsLrJp9P0lUc5dDl1/UM-Service?node-id=0%3A1) for the design. You can tweak the design if you can make it look better.

**Comment by poonammohata** [comment]
@heyrandhir I would like to work on this task, will share the ETA by tomorrow
