### ISSUE TITLE
UI Improvement 

### ISSUE THREAD

**Issue by bhk31** [Real-Dev-Squad/website-dashboard#24]
We can do following improvement for better UI experience

- Make status drop down similar to other input.
- Add space between Completion Award: and Gold as well in  Loss Rate: and Gold.
- Inline is noteworthy and checkbox.

**Comment by dimky01** [comment]
I will be working on this.

**Comment by bhk31** [comment]
@dimky01 I have already worked on this under this [PR](https://github.com/Real-Dev-Squad/website-dashboard/pull/23)

**Comment by dimky01** [comment]
Alright

**Comment by aman7870** [comment]
Thanks @bhk31 for solving this issue.
