### ISSUE TITLE
Change level value to level name

### ISSUE THREAD

**Issue by Neenu-12** [Real-Dev-Squad/website-dashboard#279]
Currently we are getting level values in the UI we want it to be level names instead.

**Comment by dostonnabotov** [comment]
Hi, @Neenu-12! Can you elaborate more on the issue? I would be happy to pick this up and fix it

**Comment by Neenu-12** [comment]
Hi, @dostonnabotov thanks for reaching out, I'm currently working on it.

**Comment by Neenu-12** [comment]
@vinayak-trivedi I have a question, can you please help me ?
