### ISSUE TITLE
Missing Favicon and Title change

### ISSUE THREAD

**Issue by sahsisunny** [Real-Dev-Squad/website-dashboard#294]
### Missing Favicon and Title change

The dashboard web app is missing a favicon, which can make it difficult for users to quickly identify the website in their browser's tabs or bookmarks. Also, the title of the dashboard web app is not descriptive and does not match the name of the web app.

#### Steps to reproduce
1. Open the dashboard web app in a web browser
2. Inspect the web page and notice the missing favicon and the title of the web app

#### Expected behavior
- The dashboard web app should have a favicon that is displayed in the browser's tabs and bookmarks.
- The title of the dashboard web app should be descriptive and match the name of the web app.

#### Actual behavior
- There is no favicon displayed in the browser's tabs or bookmarks.
- The title of the web app is not descriptive and does not match the name of the web app.

#### Suggested solution
- Add a favicon to the web app, using the appropriate file format (e.g. .ico, .png) and size (e.g. 16x16 pixels)
- Add a link to the favicon in the `<head>` of the HTML file, using the `<link>` element
- Change the title of the web app to a more appropriate and descriptive name
- Update the `<title>` element in the `<head>` of the HTML file with the new title

## For Solution
**Favicon Asset File** : [favicon.zip](https://github.com/Real-Dev-Squad/website-dashboard/files/10487301/favicon.zip)
**Title** : "< Page Name > | Dashboard Real Dev Squad"
**Eg. :** Create Tasks | Dashboard Real Dev Squad

**Comment by Mayuresh0072** [comment]
@sahsisunny @ankushdharkar @iAmAshuSahoo Hey , I want to work on this issue, Please assign me. Thanks.

**Comment by sahsisunny** [comment]
> @sahsisunny @ankushdharkar @iAmAshuSahoo Hey , I want to work on this issue, Please assign me. Thanks.

You are in the discord channel of Real Dev Squad ?
If you are then tag in the "new-task" channel else you can join the Real Dev Squad Discord the. Work on the task.

**Comment by Mayuresh0072** [comment]
Please send me the discord link. Also please assign me this issue as this is my college assignment. Thank You.

**Comment by sahsisunny** [comment]
> Please send me the discord link. Also please assign me this issue as this is my college assignment. Thank You.

I guess it's not an easy process Go to [Members](https://members.realdevsquad.com/) page and connect with the members and tell them that I want to join RDS.

**Comment by sahsisunny** [comment]
> @sahsisunny is it necessary to join discord then ? Please can you assign me the issue directly?

I don't think it can happen if you really want to work then you have to follow this procedure.

**Comment by Mayuresh0072** [comment]
@sahsisunny Actually , I have sent message to some members of RDS on twitter for joining RDS discord. But I have not received reply from them. Can you please convey my request to join RDS to any member who can approve me.

**Comment by sahsisunny** [comment]
fix merged in #297 PR
