### ISSUE TITLE
Design the Task Form & Add make status field dropdown

### ISSUE THREAD

**Issue by sumitd94** [Real-Dev-Squad/website-dashboard#3]
Improve the design of the task creation form, currently, it has no CSS

![image](https://user-images.githubusercontent.com/29303618/107525686-19385a00-6bdd-11eb-9653-5805431c2208.png)

Next, we need to make the `status` field a dropdown, with option values
`active, pending`

Link to the site - https://dashboard.realdevsquad.com/

**Comment by RohitKuwar** [comment]
@sumitd94 I want to work on this issue.

**Comment by sumitd94** [comment]
> @sumitd94 I want to work on this issue.

Let moses work on this, it will be a good first issue for him.
