### ISSUE TITLE
Lock the Accordions for the User Detail Screen for a general user

### ISSUE THREAD

**Issue by heyrandhir** [Real-Dev-Squad/website-dashboard#301]
- [x] Lock the Accordions for the User Detail Screen for a general user while it should be normal accordion for the superuser.
- [x] Lock icon to be next to the word itself not at the end.
- [x] the opacity of the locked sections to be less than opacity of non locked sections.
- [x] when hovered over the lock it should change to non cursor to signify that this action is disabled and a message should be displayed on the tooltip displaying `you do not have required permissions to view this`. 
   
![image](https://user-images.githubusercontent.com/97341921/215364221-640632f4-a671-4351-9c10-78d9f9d615cb.png)

**Comment by sahsisunny** [comment]
feature merged in #305 PR
