### ISSUE TITLE
Set end date to 7 days later by default

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-dashboard#32]
![image](https://user-images.githubusercontent.com/1935403/115117595-434b2700-9f54-11eb-9a2a-415c9af09e2f.png)

**Comment by Kumar85** [comment]
in JavaScript :
`const setEnded = () => {`
`     ...   "Make the Function to set the ended date"`
`}`

`setTimeout(()=> setEnded(), 604800000) // 7 days to Milliseconds`

**Comment by ankushdharkar** [comment]
@Kumar85 Can you send a PR to implement this feature please?

**Comment by harshit-kedia** [comment]
@ankushdharkar I can pick this up.

**Comment by hkedia321** [comment]
@ankushdharkar I can pick this up, if no one is working on it.
