### ISSUE TITLE
Make purpose field into a text area instead of input box

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-dashboard#33]

**Comment by Kumar85** [comment]
``<label` for="purpose">Tell us your story:</label>``

`<textarea id="purpose" name="story" rows="10" cols="30">`
`purpose...`
`</textarea>`

**Comment by ankushdharkar** [comment]
@Kumar85 Can you send a PR to implement this feature please?

**Comment by Kumar85** [comment]
https://jsfiddle.net/4zqeyvp9/

**Comment by ankushdharkar** [comment]
@Kumar85 Please send a PR

**Comment by ankushdharkar** [comment]
@Kumar85 
You should join our Discord Server: [Invite Link](https://discord.gg/w9BGk56y)

**Comment by ankushdharkar** [comment]
@Kumar85 Are you going to work on this?

**Comment by ToBuild-2021** [comment]
I am work on this.

**Comment by ankushdharkar** [comment]
@ToBuild-2021 Sure. Can you send a PR please?

**Comment by ankushdharkar** [comment]
@ToBuild-2021 Also join our community at Discord (it's free): https://discord.gg/sXazaRz6

**Comment by ToBuild-2021** [comment]
I am in .
