### ISSUE TITLE
Refactor | Replace redundant API URLs using constants. 

### ISSUE THREAD

**Issue by RitikJaiswal75** [Real-Dev-Squad/website-dashboard#333]
# Issue
Our dashboard site currently has a base constants file with `API_BASE_URL`, which was supposed to be imported into other files wherever it was required.

But I ran a global search for the URL and found every folder has a separate constant.js and the `API_BASE_URL` is being rewritten rather than using the pre-created constant.

### Image of the issue:
![image](https://user-images.githubusercontent.com/57758447/226118691-79aedc32-35d0-4623-8491-fc334e30dee3.png)

**Comment by Srinja333** [comment]
Can I work on this?

**Comment by mukadas026** [comment]
@RitikJaiswal75 Please assign this to me

**Comment by imsidkg** [comment]
Can I work on this isssue?

**Comment by S1ddG** [comment]
Hi @RitikJaiswal75 Would love to fix this one!

**Comment by musukeshu** [comment]
hi @RitikJaiswal75 . I would like to fix this one

**Comment by sahsisunny** [comment]
@FMK2312 why you open this issue ?
