### ISSUE TITLE
Update the path `users/userId/:userId` to `users/?id=abc` in dashboard site 

### ISSUE THREAD

**Issue by vikhyat187** [Real-Dev-Squad/website-dashboard#336]
**This need to be deployed along with issue** https://github.com/Real-Dev-Squad/website-backend/issues/966.

**Comment by Srinja333** [comment]
can i work on this?

**Comment by vikhyat187** [comment]
There is some change in requirement, will update the ticket and assign to you.

As there one more API `users/{userName}` so it will cause conflicts if we make the api as `users/{userId}`

**Comment by vikhyat187** [comment]
The update after discussion is, we decided to change the API `users/userId/{userId}` to `users/?id=abc`

@Srinja333 can you share your discord username, are you part of Real Dev Squad server?

**Comment by Srinja333** [comment]
Srinjay disc

**Comment by vikhyat187** [comment]
is your lift simulation done? @Srinja333

**Comment by vikhyat187** [comment]
@Srinja333 can you share an ETA, by when this task can be completed?

**Comment by Srinja333** [comment]
I will complete by tomorrow

**Comment by Srinja333** [comment]
@vikhyat187  i have done, please check it out

**Comment by vikhyat187** [comment]
Sure @Srinja333

**Comment by vikhyat187** [comment]
Please share the PR link @Srinja333
