### ISSUE TITLE
Pivot to Intro page

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-dashboard#367]
# Intro page pivot
## Overview

On user's details page, if they have an intro page, we would like a button to visit it in a new tab.

## User stories

- As a superuser, I should be able to click the intro link to go to user's previously filled intro page.

## Requirements

- Ensure some testing is done.

## Acceptance Criteria

- [ ] Superuser sees the intro page button enabled, if intro entry exists for the user
- [ ] Non superuser see the button disabled with a lock icon and popover describing missing permissions
- [ ] Intro page works when present

**Comment by meanwhile7** [comment]
It is my first task so I would be taking 8 days eta. 14/6/23
