### ISSUE TITLE
Filters users based on Current Status- ONBOARDING

### ISSUE THREAD

**Issue by shubhamsigdar1** [Real-Dev-Squad/website-dashboard#369]
# Filters users based on Current Status- ONBOARDING
## Overview

On user's page, we want in filter-container a checkbox ONBOARDING 

## User stories

- As a user, when we filter ONBOARDING  I want to see ONBOARDING user

## Requirements

- Ensure some testing is done.

## Depend on issue
-  https://github.com/Real-Dev-Squad/website-backend/issues/1144

- Link for filtering https://dashboard.realdevsquad.com/users/

**Comment by Aryex82** [comment]
@shubhamsigdar1 I would like to work on this.

**Comment by naivecoder786** [comment]
Hi @shubhamsigdar1 Can I take this task ?
