### ISSUE TITLE
[FeatureFlag] Design Feature Flags dashboard page

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-dashboard#37]
Create a page that GETS and POSTS the feature flag being turned on and off for the particular user

Design: [Figma Link](https://www.figma.com/file/nceSWbOwkPjeLaBsJCCOM7/Feature-Flags-Panel?node-id=0%3A10)

**Comment by Cartmanishere** [comment]
There are going to be three experiences here. 

1. A page for creating the feature flags
    -  This does not need fancy design. It can be a simple form page which POSTS to a backend route.
 2. A page listing the created featureFlags ([Figma link](https://www.figma.com/file/nceSWbOwkPjeLaBsJCCOM7/Feature-Flags-Panel?node-id=0%3A10))
