### ISSUE TITLE
Change `joined_discord` to `discordJoinedAt` in the `UserDetailsSection`

### ISSUE THREAD

**Issue by bhtibrewal** [Real-Dev-Squad/website-dashboard#385]
### Bug
The UI shows `Invalid date` because the attribute name is `discordJoinedAt` and not `joined_discord`

### Fix
Change `joined_discord` to `discordJoinedAt` in the `UserDetailsSection`

### Screenshot
<img width="884" alt="image" src="https://github.com/Real-Dev-Squad/website-dashboard/assets/42600164/c8e86f1f-8845-42af-bd82-fcb7fcb3d19c">

**Comment by chaithraramesh31** [comment]
I will work on this. Can you assign it to me?

**Comment by chaithraramesh31** [comment]
> I will work on this. Can you assign it to me?

@bhtibrewal

**Comment by sahsisunny** [comment]
Merge with #389
