### ISSUE TITLE
Add 3 buttons to the Dashboard site

### ISSUE THREAD

**Issue by Achintya-Chatterjee** [Real-Dev-Squad/website-dashboard#387]
**Description:**
I have been tasked with adding buttons to the dashboard site as requested by Ankush. The buttons will serve a specific purpose and should be visually consistent with the site's existing design.

**Requirements:**

The buttons should be placed below the navbar on the site's dashboard.
The buttons should have a specific design, including color #000000, width: 287px height: 103px top: 196px left: 100px border: 2px.
On click, button 1 should show Sync Discord user data were last called, button 2 should show Sync unverified
Discord users were last called and the button 3 should show Sync new joiners.

**Design Assets:** https://www.figma.com/file/Z6YLBQwbuj3QyhUTcLLdS6/Dashboards---Sync-stuff?type=design&node-id=2-5&mode=design&t=h70wsirEHIb4kONv-0

**Comment by MayurLund** [comment]
Can you assign me this task, please?
