### ISSUE TITLE
get direct link to group-role in discord-group

### ISSUE THREAD

**Issue by bhtibrewal** [Real-Dev-Squad/website-dashboard#390]
### Requirement
- add searching for group names
- if a user clicks on a group name add it to the params and make this a sharable link
example - https://dashboard.realdevsquad.com/discord-groups/group-gamers
<img width="1552" alt="image" src="https://github.com/Real-Dev-Squad/website-dashboard/assets/42600164/d1e03a5a-9c9c-4974-9033-ebc5bc644c83">

**Comment by chaithraramesh31** [comment]
@bhtibrewal I will work on this. Please assign me

**Comment by chaithraramesh31** [comment]
@bhtibrewal ETA for this issue - 12th July (need time for writing tests as I am new to it)

**Comment by sahsisunny** [comment]
Completed in #395 PR
