### ISSUE TITLE
Making Discord Users Page Responsive and Adding Footer to Dashboard Site

### ISSUE THREAD

**Issue by sahsisunny** [Real-Dev-Squad/website-dashboard#403]
**Description:**
The tasks are as follows:

1. Making the Discord Users Page Responsive: Currently, the Discord Users page on the Dashboard site (URL: https://dashboard.realdevsquad.com/users/discord/) is not responsive, which means it does not adapt well to different screen sizes and devices. This issue ticket aims to rectify this problem and ensure that the Discord Users page is responsive across various platforms, such as desktop, tablet, and mobile.
2. Adding a Footer to the Dashboard Site: The Dashboard site (URL: https://dashboard.realdevsquad.com/) lacks a footer section, which typically contains important links, copyright information, and other relevant details. This issue ticket requests the implementation of a footer for the Dashboard site, which will enhance the overall user experience and provide essential information at the bottom of the page.

**URL:** https://dashboard.realdevsquad.com/users/discord/

**Additional Notes:**
Please ensure that the responsive design for the Discord Users page is implemented using best practices and follows modern web standards. The goal is to create a seamless experience for users across different devices, without compromising on functionality or aesthetics. As for the footer, it should be consistent with the site's design and include necessary links and information as determined by the development team.

**Image:**
![image](https://github.com/Real-Dev-Squad/website-dashboard/assets/70854507/570c0eb8-1ee9-46db-a45e-79952470ba95)

**Comment by ankitbajpai65** [comment]
Hey @sahsisunny, I am working on this issue, created the ticket as well and got assigned from status site. Can you please close this ticket mentioning my ticket?

Ticket - https://github.com/Real-Dev-Squad/website-dashboard/issues/540
