### ISSUE TITLE
Update Dashboard Site Users Route to Reflect Filtered State in URL

### ISSUE THREAD

**Issue by RitikJaiswal75** [Real-Dev-Squad/website-dashboard#432]
# Update Dashboard Site Users Route to Reflect Filtered State in URL

## Issue Description

**Current Behavior:**
In the dashboard site users route, when we apply filters to view specific user data, the URL parameters do not change accordingly. This means that the filtered state is not represented in the URL, making it difficult to share the filtered view with others or return to the same filtered state when accessing the URL again.

**Expected Behavior:**
When applying filters to view a specific subset of users, the URL parameters should be updated to reflect the filtered state. This will allow users to share the filtered URL with others, and when someone accesses the filtered URL, they should land on the page with the same filters enabled.

## Steps to Reproduce

1. Navigate to the dashboard site users' route.
2. Observe the URL before applying any filters.
3. Apply one or more filters to view specific user data.
4. Notice that the URL parameters do not change to represent the applied filters.
5. Try sharing the URL with someone else or reloading the page with the filtered state; the filters do not persist.

## Proposed Solution

- Implement a mechanism to update the URL parameters when filters are applied, reflecting the filtered state.
- Ensure that when the filtered URL is accessed, the page displays the same filters enabled as indicated in the URL.
- Provide a way to clear filters or reset the URL to the default state.

## Additional Information

- The dashboard site is built using HTML CSS and Vanilla Js.

## Acceptance Criteria

- The URL parameters should change to represent the applied filters when filtering users.
- Accessing the filtered URL should load the page with the same filters enabled.
- Filters should be cleared or resettable to the default state as needed.
- The changes should be thoroughly tested for various scenarios, including different combinations of filters.
- The code changes should be reviewed and approved according to the team's development workflow.

## Note

This issue involves front-end changes.  Additionally, consider the impact on existing URLs and ensure backward compatibility where necessary.

**Comment by j24m** [comment]
Hey, assign this to me.

**Comment by kotesh-arya** [comment]
Closing the issue, as it is being addressed by the PR #437
