### ISSUE TITLE
Design changes in submit button to it more responsive

### ISSUE THREAD

**Issue by aman7870** [Real-Dev-Squad/website-dashboard#44]
while opening dashboard.realdevsquad.com/tasks/create the submit button should look responsive and after filling the form there should be changes in submit button color or design.

<img width="344" alt="submit button " src="https://user-images.githubusercontent.com/26053172/122638518-2082ed80-d112-11eb-80df-054fd209ecdc.png">

**Comment by VaradAC** [comment]
I would like to take this issue

**Comment by swarajpure** [comment]
> I would like to take this issue

I guess you're already working on something other issues. Let's keep this task for someone else 🙂

**Comment by ghosharnab969** [comment]
I am interested in taking up this task.
