### ISSUE TITLE
Set up prettier CLI for consistent code formatting

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-dashboard#47]
More info: https://github.com/Real-Dev-Squad/website-www/issues/98

**Comment by swarajpure** [comment]
Should also have prettier rules set up like: https://github.com/Real-Dev-Squad/website-welcome/blob/develop/.prettierrc.json

**Comment by swarajpure** [comment]
Reserved for internal member

**Comment by abhinav1590** [comment]
I will take this issue
