### ISSUE TITLE
Change due date format for user management details

### ISSUE THREAD

**Issue by Shenoy07** [Real-Dev-Squad/website-dashboard#472]
# Overview:
Currently, when we go to https://dashboard.realdevsquad.com/users/details, in the tasks part of the profile we get due dates of the tasks. The value in the due date section is not in the correct Date time format. Please take a look at the image I've included below to get a better understanding of the issue.

## Image 1:
 
![image](https://github.com/Real-Dev-Squad/website-dashboard/assets/31709147/385dc08d-f8f8-45dc-b97c-ca84bf4239c0)

# User Stories:
* As an authorized group member, I want to view task details in a clear and user-friendly format.
* As an authorized group member, with the touch of 1 button I want to see the deadline and the number of days left before the deadline.

# Requirements:
* ![image](https://img.shields.io/badge/HTML5-E34F26?style=for-the-badge&logo=html5&logoColor=white) ![image](https://img.shields.io/badge/CSS3-1572B6?style=for-the-badge&logo=css3&logoColor=white) ![image](https://img.shields.io/badge/JavaScript-323330?style=for-the-badge&logo=javascript&logoColor=F7DF1E)
* Understanding of where the data is coming from.
* Access as a super user.
* CORS extension.

# Acceptance criteria:
- [ ] At first glance the due date should show the number of days left for the submission/ completion of #476 
- [ ] On Hovering it should show us the actual due date as well.

**Comment by gauravsinhaweb** [comment]
Is this feature behind the feature flag?
