### ISSUE TITLE
Take forward PR #34

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-dashboard#49]
The author of the PR #34 seems to be unavailable from a long time. 
Need someone to pick the PR from here and take it ahead

You can take a pull from his branch after adding his fork in your remote references, now the code is in your local machine. Now you can start working on it 🙂

**Comment by swarajpure** [comment]
Reserved for internal member

**Comment by Aditi-0725** [comment]
I will take this up.
