### ISSUE TITLE
Display the extension request audit log on the super user's dashboard

### ISSUE THREAD

**Issue by Maheima** [Real-Dev-Squad/website-dashboard#494]
The super user should be able to see the following details of a particular task:
- The time when a request was raised
- The user who raised the request
- The super user who accepted/declined it
- The super user who accepted/declined it

**Comment by ardourApeX** [comment]
[simplescreenrecorder-2023-10-14_18.37.20.webm](https://github.com/Real-Dev-Squad/website-dashboard/assets/56365512/762b1330-1b11-423d-98a1-a000c5340459)
