### ISSUE TITLE
Onboarding> 31 days failing from backend API

### ISSUE THREAD

**Issue by iamitprakash** [Real-Dev-Squad/website-dashboard#511]
As a superuser i want to see user with multiple status.

In below edge case i have selected both Active and Onboardingstatus>31 error has been observed below

{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "\"state[1]\" must be one of [OOO, ONBOARDING, IDLE, ACTIVE]"
}
![Screenshot 2023-09-12 at 1 16 33 PM](https://github.com/Real-Dev-Squad/website-dashboard/assets/34869115/3e02b602-4712-42a0-9618-0f840b11606d)

**Comment by RitikJaiswal75** [comment]
Hey @iamitprakash can you confirm if the api used here is /users/search

**Comment by Shenoy07** [comment]
Assigned to me.
