### ISSUE TITLE
Profile Icon and Name Not Displayed After GitHub Sign-In

### ISSUE THREAD

**Issue by sahsisunny** [Real-Dev-Squad/website-dashboard#530]
**Issue Description:**
When attempting to sign in with GitHub on dashboard.realdevsquad.com, the sign-in process is successful; however, the user's profile icon and name are not displayed, and the "Sign In" option persists. This issue prevents users from accessing their profiles and the associated functionality. 

**Steps to Reproduce:**
1. Go to dashboard.realdevsquad.com.
2. Click on the "Sign In with GitHub" button.
3. Complete the GitHub authentication process successfully.
5. Instead, the "Sign In" button still appears, and your profile icon and name are missing.

**Expected Behavior:**
After a successful GitHub sign-in, the user should be shown a profile icon and name displayed.

**Actual Behavior:**
The "Sign In" button still appears. Profile icon and name are not displayed.

**Screenshots/Attachments:**
![image](https://github.com/Real-Dev-Squad/website-dashboard/assets/70854507/28032c0f-118c-4416-949f-c466a0857701)

**Comment by khemchand-twt11** [comment]
working on this issue.
