### ISSUE TITLE
UI/UX Improvements

### ISSUE THREAD

**Issue by ardourApeX** [Real-Dev-Squad/website-dashboard#600]
### Issue Description

1. While rendering audit logs, it introduces an additional scroll in the UI, which results in a poor user experience, as there are now two scrollable areas.
2. Committed hours disappear from the screen as soon as the user removes the mouse
3. Committed hours showing NA
4. Some extension request tiles remain disabled due to some reason 

### Expected Behaviour

- [ ] As a user, I want audit logs to take up the full height instead of displaying the scrollbar. 
- [ ] Add a delay in making committed hours invisible once the user moves the mouse away from it.
- [ ] Committed hours should stand out if not found for a user. Make it red or come up with a UI.
- [ ] Extension request tile should not remain disabled forever even if some error occurs

### Current Behavior
1. The user has 2 scrollable areas. One to get through all the extension requests and another inside extension request's accordion to view all the logs, making it a bad UX.
2. The user needs to hover again and again, to view committed hours as it goes off the screen as soon as you remove the mouse cursor from over it.
3. Make committed hours stand out if found NA.
4. Extension cards should not remain disabled forever, be it any use case or error.

### Screenshots

[simplescreenrecorder-2023-10-31_09.23.55.webm](https://github.com/Real-Dev-Squad/website-dashboard/assets/56365512/254e6fea-4898-49cf-87b6-84ed05a9b688)

### Reproducibility

 - [x] This issue is reproducible
-  [ ] This issue is not reproducible

### Steps to Reproduce
1. Start the dashboard and backend on local
6. Visit `/extension-requests/?dev=true`
7. Notice the issues mentioned above

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [x] Medium
 - [ ] Low

### Additional Information
For committed hours, do take approval prior to the implementation.

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

**Comment by shubhamjaintech** [comment]
![image](https://github.com/Real-Dev-Squad/website-dashboard/assets/22474104/e9bbe527-ffbd-4d22-a9bb-224b7839a617)

Verified in Prod
