### ISSUE TITLE
Render GitHub issue on task request

### ISSUE THREAD

**Issue by skv93-coder** [Real-Dev-Squad/website-dashboard#625]
## Title
Render issue in task request page

## Overview
Currently user can not see the GitHub issue before approval or rejection. For this he has to go to GitHub. 

## User story
On opening the task request details page I should be able to see the details of GitHub issue related to current task if the request type is creation otherwise show the task details page.

## Requirements
Use www.showdownjs.com for rendering GitHub markup

## Acceptance criteria
As a user, I should be able to see details of GitHub issue before approving the given task and after approval i should be able to see the task details

**Comment by Ajeyakrishna-k** [comment]
Please also take care of this case:  When task requestType is ASSIGNMENT task details should be shown to the user. This UI currently exists
