### ISSUE TITLE
Request for UI Development: Request Management Page

### ISSUE THREAD

**Issue by sahsisunny** [Real-Dev-Squad/website-dashboard#693]
**Description:**
Develop a Request Management Page that allows super users to view, update, approve, or reject different types of requests. The page should include multiple tabs to switch between different types of requests.

**Features:**
1. **List Requests:**
   - Implement a tabbed interface to categorize requests (e.g., OOO, Extension, Task ).
   - Fetch and display requests using the GET API: `/requests?dev=true`.
   - Include relevant details for each request.

2. **Update Requests:**
   - Provide an interface for super users to update requests.
   - Implement a form or modal for updating requests, utilizing the PUT API: `/requests?dev=true`.
   - Integrate functionality to approve or reject requests.

**Integration:**
   - Ensure seamless integration with the backend through the provided GET and PUT APIs.

**Notes:**
   - Design the UI to be user-friendly and intuitive.
   - Include error handling and user feedback for successful and unsuccessful actions.
   - Consider implementing loading indicators during API calls.

**Additional Information:**
If you require further clarification or additional information, please feel free to reach out to @sahsisunny

**Comment by sahsisunny** [comment]
# Sample Data

```json
[
  {
    "id": "MpykhM8sT1Tlid4Y6Y0d",
    "requestedBy": "user456",
    "state": "APPROVED",
    "from": 1709525300000,
    "until": 1709870800000,
    "message": "Attending a work conference.",
    "createdAt": 1709525400000,
    "updatedAt": 1709827800000,
    "lastModifiedBy": "adminUser",
    "reason": "Welcome back! Enjoy the conference."
  },
  {
    "id": "Me8sT1Tlid4Y6Y0d",
    "requestedBy": "user789",
    "state": "REJECTED",
    "from": 1709603700000,
    "until": 1709785600000,
    "message": "Out of office for personal reasons.",
    "createdAt": 1708763200000,
    "updatedAt": 1708841500000,
    "lastModifiedBy": "adminUser",
    "reason": "Sorry, we can't approve additional leave at this time."
  },
  {
    "id": "abc123",
    "requestedBy": "user101",
    "state": "PENDING",
    "from": 1710000000000,
    "until": 1711000000000,
    "message": "Family vacation.",
    "createdAt": 1709999999999,
    "updatedAt": 1710000000000
  },
  {
    "id": "def456",
    "requestedBy": "user202",
    "state": "APPROVED",
    "from": 1712000000000,
    "until": 1713000000000,
    "message": "Remote work due to personal reasons.",
    "createdAt": 1711999999999,
    "updatedAt": 1712000000000,
    "lastModifiedBy": "adminUser",
    "reason": "Understood. Make sure to stay connected during remote work."
  }
]
```

**Comment by sahsisunny** [comment]
https://dashboard.realdevsquad.com/task-requests/
https://dashboard.realdevsquad.com/extension-requests?

**Comment by palakgupta2712** [comment]
@sahsisunny Can I pick this up?

**Comment by Swapnil099** [comment]
@sahsisunny as discussed, I have created a TCR for this task. will inform here once it is approved. Thanks
