### ISSUE TITLE
Add Query Parameters and Persist State in Task-Requests Page

### ISSUE THREAD

**Issue by VinayakaHegade** [Real-Dev-Squad/website-dashboard#697]
### Issue Description

Add query parameters to the URL to reflect the filters and sorting applied, and also persist the state of the task-requests listing page.

ETA - 22 Feb, 2024. (3-4 days design doc, 4 days code change, PR Review 3 days, dev to main sync 2 days and buffer)

### Parent Issue
- #696 

### Expected Behavior

The applied filters and sorting options should be reflected in the URL. The state of the page should persist even after refreshing the page.

### Current Behavior

Currently, the applied filters and sorting options are not reflected in the URL, and the state of the page does not persist.

### Reproducibility

 - [x] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. Visit the task-requests listing page.
2. Apply filters and sorting options.

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [x] Medium
 - [ ] Low

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

**Comment by iamitprakash** [comment]
Design doc https://docs.google.com/document/d/1tHczCs9jfLctEI1xhW-ukodG7pgUzcmRxl2LE7Bk3gI/edit?pli=1#heading=h.noedhi39w6xt
