### ISSUE TITLE
Purpose input box width going out of the main container

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-dashboard#73]
While playing with the dimensions of the input box for `purpose`, it goes beyond main container which is a problem

![image](https://user-images.githubusercontent.com/56217868/126864513-7c2c09e5-3928-418b-8d55-7090a2f86567.png)

https://dashboard.realdevsquad.com/task/create.html

**Comment by kothawade29** [comment]
Could you assign this task to me?

**Comment by oskorp** [comment]
can i work on this issue ?
