### ISSUE TITLE
Move footer on the bottom of the screen

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-dashboard#77]
This should appear as the last thing on the page.
If there is not enough content on the screen, it should stick to the bottom of the viewport

![image](https://user-images.githubusercontent.com/1935403/129299636-4d39ccfd-2b4a-44b0-8a3a-7d4fad4ddb65.png)

**Comment by MukulKolpe** [comment]
@ankushdharkar can I work on this issue??

**Comment by riyaku11** [comment]
I would like to work on this issue.

**Comment by ankushdharkar** [comment]
@MukulKolpe Assigned to you. 

Sorry @riyaku11, Could you take up this please: https://github.com/Real-Dev-Squad/website-dashboard/issues/79?

**Comment by riyaku11** [comment]
Yes, can you assign #79 to me?
