### ISSUE TITLE
show user application by it's id 

### ISSUE THREAD

**Issue by vinit717** [Real-Dev-Squad/website-dashboard#783]
### Issue Description
If super pass id=<applicationid> in query params in application route then it render the particular application to UI 

### Reproducibility

 - [ ] This issue is reproducible
 - [x] This issue is not reproducible

### Severity/Priority
 - [ ] Critical
 - [x] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

**Comment by Asin-Junior-Honore** [comment]
@vinit717 please what is the status on this please, are you working on this or it still up for grabs🤧
