### ISSUE TITLE
Fix status query param on applications page

### ISSUE THREAD

**Issue by samarpan1738** [Real-Dev-Squad/website-dashboard#797]
### Issue Description

When a status filter is applied without clearing the existing status filter, a new query param is added in the URL with the same name and new status value.

### Expected Behavior

The status query param's value should be updated in the URL instead of adding a new status query param
For example: On selecting the rejected filter , URL = `/applications/?status=rejected`
On selecting the accepted filter, URL = `/applications/?status=accepted`
### Current Behavior

On selecting the rejected filter , URL = `/applications/?status=rejected`
On selected the accepted filter, URL = `/applications/?status=rejected&status=accepted`
And so on if we keep changing the status filter value without clearing it
### Screenshots

https://github.com/user-attachments/assets/1ff8be28-5d0f-41db-93bf-9e9c95ed0349

### Reproducibility
 - [X] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. Go to the `/applications` page
2. Apply the rejected status filter.
3. Apply the accepted status filter.

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [X] Medium
 - [ ] Low

### Checklist

- [X] I have read and followed the project's code of conduct.
- [X] I have searched for similar issues before creating this one.
- [X] I have provided all the necessary information to understand and reproduce the issue.
- [X] I am willing to contribute to the resolution of this issue.

**Comment by AJAY0993** [comment]
can i take up on this ? am new to open source
