### ISSUE TITLE
Feature to Edit Extension Requests Before Approval

### ISSUE THREAD

**Issue by tanu-chahal** [Real-Dev-Squad/website-dashboard#877]
### Issue Description
Currently, once a user raises an extension request, they are unable to edit it due to backend limitations. While the UI for editing exists, it does not function as expected because the backend does not yet support updates for pending extension requests.

### Expected Behavior
Users should be able to edit extension requests if they have not yet been approved. Once an extension request is approved, it should become locked for editing.

### Current Behavior
 Users can access the edit option for pending requests, but after attempting to save, the updates are not applied.

### Reproducibility

 - [x] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. Raise an extension request as a user.
2. Try to edit the request before it is approved.
3. Observe that the UI allows editing, but changes are not saved due to the lack of backend support for updates on pending requests.

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [x] Low

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

**Comment by vinit717** [comment]
By reading the issue ticket it seems the frontend is ready.
So you will need to do backend changes and can transfer this issue to backend

**Comment by tanu-chahal** [comment]
Someone is already working on backend part. Can you verify if the Edit feature UI is available in prod or not? I can't create ERs as I don't have any task approved.
