### ISSUE TITLE
UI Misalignment and Broken Layout on User Application

### ISSUE THREAD

**Issue by vinit717** [Real-Dev-Squad/website-dashboard#912]
### Issue Description
There is a critical UI misalignment and broken layout observed in the user application interface. This issue affects user navigation and usability, creating a frustrating experience and impairing core functionalities.

### Screenshots
![image](https://github.com/user-attachments/assets/b10cead0-a1a2-44bc-937b-25d341104998)
![image](https://github.com/user-attachments/assets/64e48796-10af-4c72-b9c3-ff5b0148996a)

### Reproducibility

 - [ ] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. 
2. 

### Severity/Priority
 - [ ] Critical
 - [x] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

**Comment by vamsi4845** [comment]
I can work on this

**Comment by vinit717** [comment]
> I can work on this

@vamsi4845 assigned please create a TCR for it
