### ISSUE TITLE
Bug: footer not at the bottom on mainpage

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-dashboard#92]
On https://dashboard.realdevsquad.com/, you'll see:
![image](https://user-images.githubusercontent.com/56217868/131016768-aa855f6d-f140-4408-8b5f-9ed0671b4c07.png)

The line `The contents of this website are deployed from this open sourced repo` is supposed to be a footer and it should be at the bottom of the page. Have a look here, how it should be: https://dashboard.realdevsquad.com/task/create.html

We could have a simple text like `Welcome to the dashboard site!` in the center of the screen as a heading maybe?

**Comment by aman7870** [comment]
issue is fixed
