### ISSUE TITLE
Make Create Task button responsive 

### ISSUE THREAD

**Issue by aman7870** [Real-Dev-Squad/website-dashboard#99]
![pop](https://user-images.githubusercontent.com/26053172/136317986-493ec656-63ad-431b-a03d-87cbe61eb2ef.png)

**Comment by ShivamPali-2020** [comment]
Can you assign this task to me

**Comment by ShivamPali-2020** [comment]
Hi Aman, 
I think the button is already responsive.
can you brief me about the issue once in detail.
Thanks

**Comment by aman7870** [comment]
Yes @ShivamPali-2020 upon hovering Create Task button should change color to deep blue similar to Navbar's color
